### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by firewater2** [agrausem/beets-artistcountry#4]
Should this still work? On my end:

```
** error loading plugin artistcountry:
Traceback (most recent call last):
  File "c:\users\redacted\appdata\local\programs\python\python36-32\lib\site-packages\beets\plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "c:\users\redacted\appdata\local\programs\python\python36-32\lib\site-packages\beetsplug\artistcountry.py", line 22
    print "No country for %s" % artist_item['artist']['name']
                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "No country for %s" % artist_item['artist']['name'])?
```

Furhtermore - the reason I'm interested on the plugin is that I want a way to tag all possible albums with their country of origin. Can this be done with this plugin, or is it only for folder structures?

**Comment by agrausem** [comment]
I fix the library to support  python3.4+ versions. It should work, but you need to upgrade to 0.2.0 version.

It is only for folder structures. I believe there is no official tag for country purpose, but I could be wrong. Can you tell me if there is one ?
